name = "Lean4-Real-Construction"
version = "0.1.0"
defaultTargets = ["lean4-real-construction"]

[[lean_lib]]
name = "Lean4RealConstruction"

[[lean_exe]]
name = "lean4-real-construction"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "Paperproof"
git = "https://github.com/Paper-Proof/paperproof.git"
subDir = "lean"
rev = "main"

[[require]]
name = "doc-gen4"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"