name: "Deploy Interactive Docs"
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Lean
        uses: leanprover/lean-action@v1
        with:
          auto-bundle: false

      - name: Build and Generate Docs
        run: |
          # 1. 下載、進入 doc-gen4 目錄編譯
          git clone https://github.com/leanprover/doc-gen4.git
          cd doc-gen4
          elan override set $(cat ../lean-toolchain)
          lake build
          # 取得 doc-gen4 執行檔的絕對路徑
          DOCGEN_EXE="$(pwd)/.lake/build/bin/doc-gen4"
          cd ..

          # 2. 回到根目錄編譯你的主專案 (確保 olean 檔案存在)
          lake build

          # 3. 執行生成 Lean4RealConstruction
          lake build Lean4RealConstruction:docs
          doc-gen4 -h

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.lake/build/doc'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
